const initial=[
 {id:1,name:'Løpevest, syntetisk eksempel',sku:'DEMO-VEST-01',category:'Bekledning',qty:24,location:'Hovedlager',status:'Tilgjengelig',value:390},
 {id:2,name:'Førstehjelpssett, syntetisk eksempel',sku:'DEMO-SIK-02',category:'Sikkerhet',qty:8,location:'Bod A',status:'Tilgjengelig',value:520},
 {id:3,name:'Målportal, syntetisk eksempel',sku:'DEMO-START-03',category:'Start/mål',qty:2,location:'Tilhenger',status:'Reservert (til løp)',value:2100}
];
let items=structuredClone(initial), tab='varer', query='';
const view=document.querySelector('#view');
const esc=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const nok=n=>new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:0}).format(n);
function itemTable(rows){return `<div class="panel"><div class="table-wrap"><table><thead><tr><th>Utstyr</th><th>Kategori</th><th>Status</th><th>Antall</th><th>Plassering</th><th>Estimert verdi</th><th>Handlinger</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.sku)}</small></td><td>${esc(x.category)}</td><td><span class="tag">${esc(x.status)}</span></td><td>${x.qty}</td><td>${esc(x.location)}</td><td>${nok(x.qty*x.value)}</td><td><div class="row-actions"><button data-action="detail" data-id="${x.id}">Vis</button><button data-action="edit" data-id="${x.id}">Rediger</button><button data-action="adjust" data-id="${x.id}">Juster antall</button><button data-action="delete" data-id="${x.id}">Slett</button></div></td></tr>`).join('')}</tbody></table>${rows.length?'':'<p class="empty">Ingen utstyr samsvarer med søket.</p>'}</div></div>`}
function render(){const rows=items.filter(x=>(x.name+' '+x.sku).toLowerCase().includes(query));let html='';
 if(tab==='varer')html=`<div class="summary"><div class="metric"><span>Utstyrstyper</span><strong>${items.length}</strong></div><div class="metric"><span>Antall på lager</span><strong>${items.reduce((a,x)=>a+x.qty,0)}</strong></div><div class="metric"><span>Estimert verdi</span><strong>${nok(items.reduce((a,x)=>a+x.qty*x.value,0))}</strong></div></div>${itemTable(rows)}<div class="panel"><h2>Unike enheter</h2><p>Eksempelenhet · DEMO-ENHET-01 · knyttet til Målportal · Tilgjengelig · Tilhenger</p><p class="muted">I kildeløsningen kan enheter ha egen status, plassering, tilstand og serienummer.</p></div>`;
 if(tab==='utleie')html=`<div class="panel"><h2>Utleie</h2><p>Leietakere, avtaler og vilkår vises her i den fullstendige WordPress-løsningen.</p><p><strong>Syntetisk eksempelavtale:</strong> Demoarrangør · 2 løpevester · 12.–14. juni · Kladd</p><button data-action="activate">Aktiver eksempelavtale</button> <button data-action="return">Registrer eksempelretur</button><p class="muted">Ingen leietakerregister, kontaktinformasjon eller lagret avtale finnes her.</p>${itemTable(items.slice(0,1))}</div>`;
 if(tab==='rapporter')html=`<div class="panel"><h2>Rapporter</h2><div class="summary"><div class="metric"><span>Total innkjøpsverdi (eksempel)</span><strong>${nok(items.reduce((a,x)=>a+x.qty*x.value*.8,0))}</strong></div><div class="metric"><span>Estimert verdi</span><strong>${nok(items.reduce((a,x)=>a+x.qty*x.value,0))}</strong></div></div><h3>Verdi per kategori</h3><div class="tiles">${[...new Set(items.map(x=>x.category))].map(c=>`<div class="tile"><strong>${c}</strong><p>${nok(items.filter(x=>x.category===c).reduce((a,x)=>a+x.qty*x.value,0))}</p></div>`).join('')}</div></div>`;
 if(tab==='delte')html=`<div class="panel"><h2>Delte lister</h2><p>Kilden støtter tidsbegrensede leselenker. I denne demoen opprettes ingen lenker eller tilgangstokener.</p><button data-action="share">Forhåndsvis syntetisk leseliste</button><div id="share-preview"></div></div>`;
 if(tab==='import')html=`<div class="panel"><h2>Import/eksport</h2><p>Kildens portal støtter CSV-import og XLSX-eksport. Ingen fil behandles eller lastes ned i demoen.</p><div class="tiles"><div class="tile"><h3>Importer utstyr</h3><p>Eksempelflyt, deaktivert for å unngå opplasting.</p><button disabled>Velg importfil</button></div><div class="tile"><h3>Eksporter utvalg</h3><p>Vis syntetisk forhåndsvisning av rader.</p><button data-action="export">Vis eksempel</button></div></div><div id="export-preview"></div></div>`;
 if(tab==='opptelling')html=`<div class="panel"><h2>Lageropptelling / justering</h2><p>Registrer en syntetisk opptelling og se hvordan et avvik ville blitt håndtert. Ingenting blir lagret.</p>${items.map(x=>`<div class="tile"><strong>${esc(x.name)}</strong> · registrert antall: ${x.qty}<div class="row-actions"><input aria-label="Opptalt antall for ${esc(x.name)}" type="number" min="0" value="${x.qty}" data-count="${x.id}"><button data-action="count" data-id="${x.id}">Sammenlign</button></div><span id="count-${x.id}" role="status"></span></div>`).join('')}</div>`;
 if(tab==='innstillinger')html=`<div class="panel"><h2>Innstillinger</h2><p>Eksempellister som i kilden kan administreres fra innstillinger. Endringer er ikke tilgjengelige her.</p><div class="tiles">${[['Kategorier','Bekledning · Sikkerhet · Start/mål'],['Plasseringer','Hovedlager · Bod A · Tilhenger'],['Statuser','Tilgjengelig · Utleid / utlånt · Reservert · Defekt'],['Løp','Syntetisk eksempelarrangement'],['Vedleggskategorier','Bruksanvisning · Kvittering · Sertifikat'],['Metadatafelter','Størrelse · Vekt (gram) · ekstra felter']].map(([h,p])=>`<div class="tile"><h3>${h}</h3><p>${p}</p><button disabled>Administrer (ikke aktiv i demo)</button></div>`).join('')}</div></div>`;
 view.innerHTML=html;
}
document.querySelectorAll('[role=tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('[role=tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));render()}));
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value.toLowerCase();render()});
function openForm(item){const d=document.querySelector('#item-dialog'),f=document.querySelector('#item-form');f.reset();f.elements.name.value=item?.name||'';f.elements.sku.value=item?.sku||'';f.elements.category.value=item?.category||'Bekledning';f.elements.qty.value=item?.qty??1;f.elements.location.value=item?.location||'Hovedlager';f.elements.value.value=item?.value??0;d.dataset.edit=item?.id||'';document.querySelector('#dialog-title').textContent=item?'Rediger utstyr':'Legg til utstyr';d.showModal()}
document.querySelector('#add-item').addEventListener('click',()=>openForm());
const itemForm=document.querySelector('#item-form');itemForm.addEventListener('submit',(event)=>event.preventDefault());
document.querySelector('#save-item').addEventListener('click',e=>{e.preventDefault();const f=document.querySelector('#item-form');if(!f.reportValidity())return;const id=Number(document.querySelector('#item-dialog').dataset.edit),data={name:f.elements.name.value,sku:f.elements.sku.value,category:f.elements.category.value,qty:Number(f.elements.qty.value),location:f.elements.location.value,status:'Tilgjengelig',value:Number(f.elements.value.value)};if(id)items=items.map(x=>x.id===id?{...x,...data}:x);else items.push({id:Date.now(),...data});document.querySelector('#item-dialog').close();render()});
view.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=Number(b.dataset.id),x=items.find(i=>i.id===id);switch(b.dataset.action){case'detail':b.closest('tr').insertAdjacentHTML('afterend',`<tr><td colspan="7"><strong>${esc(x.name)}</strong> · SKU ${esc(x.sku)} · ${esc(x.category)} · status ${esc(x.status)} · ${x.qty} stk · ${esc(x.location)} · estimert verdi ${nok(x.qty*x.value)}<br>Instruks, vedlegg, notater og historikk er ikke aktivert i demoen.</td></tr>`);break;case'edit':openForm(x);break;case'adjust':{const n=Number(prompt('Syntetisk justering (+/- antall):','1'));if(Number.isFinite(n)){x.qty=Math.max(0,x.qty+n);render()}break}case'delete':items=items.filter(i=>i.id!==id);render();break;case'activate':b.textContent='Eksempelavtale aktivert lokalt';break;case'return':b.textContent='Eksempelretur registrert lokalt';break;case'share':document.querySelector('#share-preview').innerHTML=`<h3>Leseliste · syntetisk eksempel</h3>${itemTable(items)}`;break;case'export':document.querySelector('#export-preview').innerHTML=`<h3>Eksportforhåndsvisning</h3>${itemTable(items)}`;break;case'count':{const input=view.querySelector(`[data-count="${id}"]`),delta=Number(input.value)-x.qty;document.querySelector(`#count-${id}`).textContent=delta===0?'Opptalt antall stemmer.':`Avvik: ${delta>0?'+':''}${delta} stk · velg en årsak i den fullstendige løsningen.`;break}}});
render();
